### ISSUE TITLE
Transformer no longer working on playground

### ISSUE THREAD

**Issue by kwasimensah** [orta/playground-transformer-timeline#7]
I tried to use the transformer on this playground example

https://www.typescriptlang.org/play?esModuleInterop=false&target=9&module=100&isolatedModules=false&allowSyntheticDefaultImports=false#code/JYWwDg9gTgLgBAbwMZQKYEMaoBLoM4AWAvnAGZQQhwBEKAnmDBNQNwBQbqAHpLIihiy5CRDkA

After you hit the "Generate transform stages" button, you'll see errors in the javascript console

**Comment by orta** [comment]
Interesting, a compiler crash is certainly unexpected - maybe the API changed under the hood

**Comment by beerose** [comment]
This issue can be closed — resolved at: https://github.com/orta/playground-transformer-timeline/pull/8
